### ISSUE TITLE
More predicates

### ISSUE THREAD

**Issue by DanielVandH** [JuliaGeometry/AdaptivePredicates.jl#2]
Nice to see something like this exist - I had gotten halfway to doing something like this before abandoning it, so glad someone was able to. Do you have plans on implementing other predicates like `incircle`, `orient3d`, etc? I could try and get to it eventually if that is of interest, but just wanted to see if you had anything else in mind.

**Comment by vchuravy** [comment]
I personally have no need for this code and I would be happy to hand it over to someone.

I just did it quickly to help a friend.

**Comment by DanielVandH** [comment]
That's fair enough. I might be interested in working on this eventually since I do need it, so maybe I'll write back if I want to work on it but until then I can leave it as is. Thanks for your reply! I'll close this issue.

**Comment by DanielVandH** [comment]
> I personally have no need for this code and I would be happy to hand it over to someone.

@vchuravy Actually, would you mind if I did take over for the code? I'm happy to continue making PRs for you to review if that's what you prefer over me making commits directly.

**Comment by vchuravy** [comment]
Should we just move this code over to JuliaGeometry?

**Comment by DanielVandH** [comment]
Sure. Are you a member of JuliaGeometry already to do the transfer? I don't think I can invite you

**Comment by asinghvi17** [comment]
I just invited you to JuliaGeometry @vchuravy

**Comment by DanielVandH** [comment]
Thanks @asinghvi17!

Am I able to have committing rights for the repo?

**Comment by asinghvi17** [comment]
Yes, I added you as admin here as well.
