### ISSUE TITLE
Tests failing, or my machine is bad

### ISSUE THREAD

**Issue by DanielVandH** [JuliaGeometry/AdaptivePredicates.jl#4]
Maybe my fix to compiling predicates.c has failed somewhere, but it seems the tests are failing here:

```julia
julia> @check function orient_against_exact(a=complexgen, b=complexgen, c=complexgen)
           dir = orient(a,b,c)
           event!("Adaptive", dir)
           edir = ExactPredicates.orient(a,b,c)
           event!("Exact", edir)
           dir == edir
       end
Found counterexample
  Context: orient_against_exact

  Arguments:
      a::ComplexF64 = 0.0 + 0.0im
      b::ComplexF64 = 0.0 + 5.0e-324im
      c::ComplexF64 = 5.0e-324 + 0.0im

  Events:
    Adaptive
        0
    Exact
        -1

julia> @check function orient_c_against_exact(a=complexgen, b=complexgen, c=complexgen)
           dir = CPredicates.orient(a,b,c)
           event!("Original", dir)
           edir = ExactPredicates.orient(a,b,c)
           event!("Exact", edir)
           dir == edir
       end
Found counterexample
  Context: orient_c_against_exact

  Arguments:
      a::ComplexF64 = 0.0 + 0.0im
      b::ComplexF64 = 0.0 + 5.0e-324im
      c::ComplexF64 = 5.0e-324 + 0.0im

  Events:
    Original
        0
    Exact
        -1
```

If you have the time, Is this something you're able to please see if you can reproduce? I'm on a Windows machine and so can't check the results without #3 which changes the .c file

(Also, the `Exact` result is probably the correct one since `orient(a, b, c) = -2.5e-647`)

**Comment by vchuravy** [comment]
IIRC these failures are expected and consistent with the original implementation.

**Comment by DanielVandH** [comment]
Ah, indeed you are right. From the paper:

> This article does not address issues of overflow and underflow, so I allow the exponent
to be an integer in the range $[-\infty, \infty]$. (Fortunately, many applications have inputs whose exponents fall
within a circumscribed range. The four predicates implemented for this article will not overflow nor un-
derflow if their inputs have exponents in the range $[-142, 201]$ and IEEE 754 double precision arithmetic
is used.)

Maybe I should be checking in those tests that `exponent(x) in (-142:201)` for `x in abs.(a.re, a.im, b.re, b.im, c.re, c.im)` then.
